id: amplitude
namespace: des.amplitude

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: hello
        type: io.kestra.plugin.core.log.Log
        message: Hello World! 🚀

      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/duongthomaas/deng_amplitude_project
        branch: main
        username: "{{ kv('github_user') }}"
        password: "{{ kv('github_token') }}"

      - id: python_scripts
        type: io.kestra.plugin.scripts.python.Commands
        env:
          AWS_ACCESS_KEY: "{{ kv('AWS_ACCESS_KEY') }}"
          AWS_SECRET_KEY: "{{ kv('AWS_SECRET_KEY') }}"
          AMP_API_KEY: "{{ kv('AMP_API_KEY') }}"
          AMP_SECRET_KEY: "{{ kv('AMP_SECRET_KEY') }}"
          AWS_REGION: "{{ kv('AWS_REGION') }}"
          bucket_name: "{{ kv('bucket_name') }}"
        beforeCommands:
          - pip install -r requirements.txt
        commands:
          - echo "😍 packages installed, starting main script"
          - python main.py
          - echo "Files uploaded, ending python script 💕"

triggers:
  - id: every_15_minutes
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
